export const quotes = [
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
  "The future depends on what you do today. — Mahatma Gandhi",
  "Act as if what you do makes a difference. It does. — William James",
  "Success is not the key to happiness. Happiness is the key to success. — Albert Schweitzer",
  "Hardships often prepare ordinary people for an extraordinary destiny. — C.S. Lewis",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "With the new day comes new strength and new thoughts. — Eleanor Roosevelt",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. — Zig Ziglar",
  "Dream big and dare to fail. — Norman Vaughan",
  "Everything you’ve ever wanted is on the other side of fear. — George Addair",
  "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
  "The harder the conflict, the greater the triumph. — George Washington",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
  "Don’t let yesterday take up too much of today. — Will Rogers",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character. — Unknown",
  "It’s not whether you get knocked down, it’s whether you get up. — Vince Lombardi",
  "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. — Steve Jobs",
  "People who are crazy enough to think they can change the world, are the ones who do. — Rob Siltanen",
  "Failure will never overtake me if my determination to succeed is strong enough. — Og Mandino",
  "We may encounter many defeats but we must not be defeated. — Maya Angelou",
  "Whether you think you can or think you can’t, you’re right. — Henry Ford",
  "Do what you can with all you have, wherever you are. — Theodore Roosevelt",
  "Don’t wait. The time will never be just right. — Napoleon Hill",
  "Things work out best for those who make the best of how things work out. — John Wooden",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. — Helen Keller",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do. — Johann Wolfgang Von Goethe",
  "The only place where success comes before work is in the dictionary. — Vidal Sassoon",
  "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
  "What you lack in talent can be made up with desire, hustle, and giving 110% all the time. — Don Zimmer",
  "Do not wait to strike till the iron is hot; but make it hot by striking. — William Butler Yeats",
  "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
  "The man who has confidence in himself gains the confidence of others. — Hasidic Proverb",
  "We generate fears while we sit. We overcome them by action. — Dr. Henry Link",
  "You don’t have to be great to start, but you have to start to be great. — Zig Ziglar",
  "Setting goals is the first step in turning the invisible into the visible. — Tony Robbins",
  "Shoot for the moon. Even if you miss, you'll land among the stars. — Norman Vincent Peale",
  "If you’re going through hell, keep going. — Winston Churchill",
  "There are no limits to what you can accomplish, except the limits you place on your own thinking. — Brian Tracy",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "Don’t be afraid to give up the good to go for the great. — John D. Rockefeller",
  "Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",
  "Opportunities don't happen. You create them. — Chris Grosser",
  "Don’t let the fear of losing be greater than the excitement of winning. — Robert Kiyosaki",
  "If you really look closely, most overnight successes took a long time. — Steve Jobs",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Do what you love and the money will follow. — Marsha Sinetar",
  "Success is not in what you have, but who you are. — Bo Bennett",
  "Be so good they can’t ignore you. — Steve Martin",
  "Turn your wounds into wisdom. — Oprah Winfrey",
  "What seems to us as bitter trials are often blessings in disguise. — Oscar Wilde",
  "Life is 10% what happens to us and 90% how we react to it. — Charles R. Swindoll",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "You don’t have to be perfect to be amazing. — Unknown",
  "Happiness is not something ready-made. It comes from your own actions. — Dalai Lama",
  "A goal without a plan is just a wish. — Antoine de Saint-Exupéry",
  "Do not let what you cannot do interfere with what you can do. — John Wooden",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. — Christian D. Larson",
  "Success is how high you bounce when you hit bottom. — George S. Patton",
  "You are braver than you believe, stronger than you seem, and smarter than you think. — A.A. Milne",
  "The difference between who you are and who you want to be is what you do. — Unknown",
  "Doubt kills more dreams than failure ever will. — Suzy Kassem",
  "The best way to predict the future is to create it. — Abraham Lincoln",
  "Fall seven times, stand up eight. — Japanese Proverb",
  "Do something today that your future self will thank you for. — Sean Patrick Flanery",
  "Your limitation—it’s only your imagination. — Unknown",
  "The harder you work for something, the greater you’ll feel when you achieve it. — Unknown",
  "Great things never come from comfort zones. — Unknown",
  "Dream it. Wish it. Do it. — Unknown",
  "Success doesn’t just find you. You have to go out and get it. — Unknown",
  "The key to success is to focus on goals, not obstacles. — Unknown",
  "Keep your face always toward the sunshine—and shadows will fall behind you. — Walt Whitman",
];
